Update build-immortalwrt-custom.yml

diff --git a/.github/workflows/build-immortalwrt-custom.yml b/.github/workflows/build-immortalwrt-custom.yml
--- a/.github/workflows/build-immortalwrt-custom.yml
+++ b/.github/workflows/build-immortalwrt-custom.yml
@@ -143,6 +143,16 @@ jobs:
           tags: immortalwrt:initial-arm64
           push: false  # 不推送镜像
 
+      - name: List local Docker images
+        run: docker images
+    
+      - name: Ensure Docker image exists
+        run: |
+          if ! docker image inspect immortalwrt:initial-arm64 &> /dev/null; then
+            echo "Image 'immortalwrt:initial-arm64' not found. Rebuilding..."
+            docker build -t immortalwrt:initial-arm64 --platform linux/arm64 ./src/arm64
+          fi
+      
       - name: Run container in immortalwrt-arm64
         run: |
           docker run -d --name immortalwrt-arm64 --platform linux/arm64 --privileged immortalwrt:initial-arm64 /bin/sh -c "while true; do sleep 1000; done"
